#Ejercico 20: Menu del dia
#Estudiante : Yoeleiny Mariasalome Barrios Zambrano
#GitHub: salome425
#Fecha:2025,11,16
print("=== RESTAURANTE \"LA TRADICIÓN\" ===")
print("  Menú Especial del Día")
print()
print("Días disponibles: Lunes a Domingo")
print()

dia = input("¿Qué día es hoy? ").lower()
print()

if dia == "lunes":
    print(" LUNES")
    print(" PLATILLO ESPECIAL:")
    print("Enchiladas verdes")
    print("Descripción:")
    print("Tortillas de maíz rellenas de pollo deshebrado,")
    print("bañadas en salsa verde cremosa, con queso y crema.")
    print("Incluye:")
    print(" Arroz rojo")
    print(" Frijoles refritos")
    print(" Agua de jamaica")
    print("Precio: $75")
    print("¡Buen provecho!")

elif dia == "martes":
    print(" MARTES")
    print(" PLATILLO ESPECIAL:")
    print("Tacos al Pastor")
    print("Descripción:")
    print("Tortillas de maíz con carne de cerdo marinada en achiote,")
    print("servidos con piña, cilantro, cebolla y salsa verde.")
    print("Incluye:")
    print(" Orden de 5 tacos")
    print(" Frijoles refritos")
    print(" Agua de horchata")
    print("Precio: $85")
    print("¡Buen provecho!")

elif dia == "miercoles" or dia == "miércoles":
    print(" MIÉRCOLES")
    print(" PLATILLO ESPECIAL:")
    print("Pozole")
    print("Descripción:")
    print("Caldo de maíz cacahuazintle con carne de cerdo,")
    print("servido con lechuga, rábano, cebolla y orégano.")
    print("Incluye:")
    print(" Tostadas con crema")
    print(" Limones y salsa picante")
    print(" Agua de tamarindo")
    print("Precio: $90")
    print("¡Buen provecho!")

elif dia == "jueves":
    print(" JUEVES")
    print(" PLATILLO ESPECIAL:")
    print("Mole con pollo")
    print("Descripción:")
    print("Pieza de pollo bañada en mole poblano tradicional,")
    print("con un toque de ajonjolí tostado.")
    print("Incluye:")
    print(" Arroz blanco")
    print(" Tortillas de maíz")
    print(" Agua de limón con chía")
    print("Precio: $95")
    print("¡Buen provecho!")

elif dia == "viernes":
    print(" VIERNES")
    print(" PLATILLO ESPECIAL:")
    print("Pescado a la veracruzana")
    print("Descripción:")
    print("Filete de huachinango en salsa de jitomate,")
    print("con alcaparras, aceitunas y chiles güeros.")
    print("Incluye:")
    print(" Arroz blanco")
    print(" Ensalada fresca")
    print(" Agua de piña")
    print("Precio: $120")
    print("¡Buen provecho!")

elif dia == "sabado" or dia == "sábado":
    print(" SÁBADO")
    print(" PLATILLO ESPECIAL:")
    print("Barbacoa")
    print("Descripción:")
    print("Carne de borrego suave cocida en penca de maguey,")
    print("servida por taco o por kilo.")
    print("Incluye:")
    print(" Consomé de borrego")
    print(" Tortillas hechas a mano")
    print(" Salsa borracha y guacamole")
    print("Precio: $100")
    print("¡Buen provecho!")

elif dia == "domingo":
    print(" DOMINGO")
    print(" PLATILLO ESPECIAL:")
    print("Menudo")
    print("Descripción:")
    print("Caldo tradicional de pancita de res con maíz cacahuazintle,")
    print("chile guajillo y especias mexicanas.")
    print("Incluye:")
    print(" Tazón grande")
    print(" Tortillas de maíz")
    print(" Limón, cebolla y orégano")
    print(" Pan bolillo")
    print("Precio: $95")
    print("¡Buen provecho!")

else:
    print(" Día no válido")
    print("Por favor ingresa un día de la semana correcto:")
    print("Lunes, Martes, Miércoles, Jueves, Viernes, Sábado, Domingo")